name: AllesLooped
version: '${project.version}'
main: io.github.aparx.challenges.looping.ChallengePlugin
api-version: 1.19
authors: [ bonedfps ]
description: \"Alles-Looped\"-Challenge für Basti
commands:
  cstart:
    description: "Startet die Challenge"
    permission: "challenge.cstart"
  cstop:
    description: "Beendet die Challenge"
    permission: "challenge.cstop"
  cpause:
    description: "Pausiert die Challenge"
    permission: "challenge.cpause"
  cinfo:
    description: "Debug-Tool um aktuelle Informationen aufzurufen"
    permission: "challenge.cinfo"